package com.wangtao.appmanager.mapper.secondary;

import com.wangtao.appmanager.model.secondary.DicItem;
import com.wangtao.appmanager.model.secondary.DicItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DicItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_item
     *
     * @mbggenerated Tue Oct 30 10:45:11 CST 2018
     */
    int countByExample(DicItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_item
     *
     * @mbggenerated Tue Oct 30 10:45:11 CST 2018
     */
    int deleteByExample(DicItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_item
     *
     * @mbggenerated Tue Oct 30 10:45:11 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_item
     *
     * @mbggenerated Tue Oct 30 10:45:11 CST 2018
     */
    int insert(DicItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_item
     *
     * @mbggenerated Tue Oct 30 10:45:11 CST 2018
     */
    int insertSelective(DicItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_item
     *
     * @mbggenerated Tue Oct 30 10:45:11 CST 2018
     */
    List<DicItem> selectByExample(DicItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_item
     *
     * @mbggenerated Tue Oct 30 10:45:11 CST 2018
     */
    DicItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_item
     *
     * @mbggenerated Tue Oct 30 10:45:11 CST 2018
     */
    int updateByExampleSelective(@Param("record") DicItem record, @Param("example") DicItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_item
     *
     * @mbggenerated Tue Oct 30 10:45:11 CST 2018
     */
    int updateByExample(@Param("record") DicItem record, @Param("example") DicItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_item
     *
     * @mbggenerated Tue Oct 30 10:45:11 CST 2018
     */
    int updateByPrimaryKeySelective(DicItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_item
     *
     * @mbggenerated Tue Oct 30 10:45:11 CST 2018
     */
    int updateByPrimaryKey(DicItem record);
}