spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: provide1
          uri: http://localhost:8081/hi
          predicates:
            - Path=/test
            - Weight=provide,90
        - id: provide2
          uri: http://localhost:8083/hi
          predicates:
            - Path=/test
            - Weight=provide,10
debug: true