package com.wangtao.appmanager.model.secondary;

public class DicItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_item.id
     *
     * @mbggenerated Tue Oct 30 10:45:11 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_item.code
     *
     * @mbggenerated Tue Oct 30 10:45:11 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_item.name
     *
     * @mbggenerated Tue Oct 30 10:45:11 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_item.description
     *
     * @mbggenerated Tue Oct 30 10:45:11 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_item.id
     *
     * @return the value of dic_item.id
     *
     * @mbggenerated Tue Oct 30 10:45:11 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_item.id
     *
     * @param id the value for dic_item.id
     *
     * @mbggenerated Tue Oct 30 10:45:11 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_item.code
     *
     * @return the value of dic_item.code
     *
     * @mbggenerated Tue Oct 30 10:45:11 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_item.code
     *
     * @param code the value for dic_item.code
     *
     * @mbggenerated Tue Oct 30 10:45:11 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_item.name
     *
     * @return the value of dic_item.name
     *
     * @mbggenerated Tue Oct 30 10:45:11 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_item.name
     *
     * @param name the value for dic_item.name
     *
     * @mbggenerated Tue Oct 30 10:45:11 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_item.description
     *
     * @return the value of dic_item.description
     *
     * @mbggenerated Tue Oct 30 10:45:11 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_item.description
     *
     * @param description the value for dic_item.description
     *
     * @mbggenerated Tue Oct 30 10:45:11 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}