package com.wangtao.appmanager.model.primary;

import java.util.Date;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.id
     *
     * @mbggenerated Tue Oct 30 10:43:01 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.password
     *
     * @mbggenerated Tue Oct 30 10:43:01 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.rememberMe
     *
     * @mbggenerated Tue Oct 30 10:43:01 CST 2018
     */
    private Boolean rememberme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.username
     *
     * @mbggenerated Tue Oct 30 10:43:01 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.last_access_time
     *
     * @mbggenerated Tue Oct 30 10:43:01 CST 2018
     */
    private Date lastAccessTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.id
     *
     * @return the value of admin.id
     *
     * @mbggenerated Tue Oct 30 10:43:01 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.id
     *
     * @param id the value for admin.id
     *
     * @mbggenerated Tue Oct 30 10:43:01 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.password
     *
     * @return the value of admin.password
     *
     * @mbggenerated Tue Oct 30 10:43:01 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.password
     *
     * @param password the value for admin.password
     *
     * @mbggenerated Tue Oct 30 10:43:01 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.rememberMe
     *
     * @return the value of admin.rememberMe
     *
     * @mbggenerated Tue Oct 30 10:43:01 CST 2018
     */
    public Boolean getRememberme() {
        return rememberme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.rememberMe
     *
     * @param rememberme the value for admin.rememberMe
     *
     * @mbggenerated Tue Oct 30 10:43:01 CST 2018
     */
    public void setRememberme(Boolean rememberme) {
        this.rememberme = rememberme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.username
     *
     * @return the value of admin.username
     *
     * @mbggenerated Tue Oct 30 10:43:01 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.username
     *
     * @param username the value for admin.username
     *
     * @mbggenerated Tue Oct 30 10:43:01 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.last_access_time
     *
     * @return the value of admin.last_access_time
     *
     * @mbggenerated Tue Oct 30 10:43:01 CST 2018
     */
    public Date getLastAccessTime() {
        return lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.last_access_time
     *
     * @param lastAccessTime the value for admin.last_access_time
     *
     * @mbggenerated Tue Oct 30 10:43:01 CST 2018
     */
    public void setLastAccessTime(Date lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }
}