
#github oauth2 setting
github:
  client:
    clientId: 1ec9fb67b06479a0bde4
    clientSecret: c580a5e42e7f8f32cbde024b78a9834273ca0ddc
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

#facebook oauth2 setting
facebook:
  client:
    clientId: 233668646673605
    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

#twitter oauth2 setting


#qq oauth2 setting


#google oauth2 setting
google:
  client:
    clientId: 233668646673605
    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

#myself oauth2 setting
myself:
  client:
    clientId: client_3
    clientSecret: $2a$10$cOf2Mzy7Nr.kVsdP13HIyewvY7DviOorG/j73IKvkQ50Vo6aYptTy
    accessTokenUri: http://localhost:8088/oauth/token
    userAuthorizationUri: http://localhost:8088/oauth/authorize
    clientAuthenticationScheme: form
#    useCurrentUri: false
#    registered-redirect-uri: http://localhost:8080/client
  resource:
    userInfoUri: http://localhost:8088/user
server:
  port: 8080
  servlet:
    context-path: /
    session:
      cookie:
        name: CLIENT_SESSIONID
logging:
  level:
    org.springframework.security.oauth2: debug