
#github oauth2 setting
github:
  client:
    clientId: 1ec9fb67b06479a0bde4
    clientSecret: c580a5e42e7f8f32cbde024b78a9834273ca0ddc
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

#facebook oauth2 setting
facebook:
  client:
    clientId: 233668646673605
    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

#twitter oauth2 setting


#qq oauth2 setting
qq:
  client:
    clientId: 233668646673605
    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

#google oauth2 setting
google:
  client:
    clientId: 233668646673605
    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

#myself oauth2 setting
myself:
  client:
    clientId: client
    clientSecret: 123456
    accessTokenUri: http://47.97.180.239:8043/uaa/oauth/token
    userAuthorizationUri: http://47.97.180.239:8043/uaa/oauth/authorize
#    客户端对访问的令牌终端授权时使用的机制。 建议值： "http_basic" 和 "form"。 默认值： "http_basic"。
#    clientAuthenticationScheme: form  加了一个form坑死自己了
#    useCurrentUri: false
#    registered-redirect-uri: http://localhost:8080/client
  resource:
    userInfoUri: http://47.97.180.239:8043/uaa/users/me

#admin oauth2 setting
admin:
  client:
    clientId: client_3
    clientSecret: 123456
    accessTokenUri: http://localhost:8088/oauth/token
    userAuthorizationUri: http://localhost:8088/oauth/authorize
    clientAuthenticationScheme: query
#    useCurrentUri: false
#    registered-redirect-uri: http://localhost:8080/client
  resource:
    userInfoUri: http://localhost:8088/user



server:
  port: 8080
  servlet:
    context-path: /
    session:
      cookie:
        name: CLIENT_SESSIONID
logging:
  level:
    org.springframework.security: debug